<center>
# End the Syndemic
</center>

## Glossary

**Endocarditis:** infection of the inner lining of heart
chambers and valves

**Osteomyelitis:** infection of the bone

**Sepsis:** the body's extreme response to an infection

**Skin, soft tissue, & venous infections (SSTVI):** infection of the skin, soft tissues, and
veins, including sepsis, endocarditis, and osteomyelitis

**Substance Use Disorder (SUDs):** persistent use of drugs (including alcohol) despite substantial harm and adverse consequences as a result of their use

**Syndemic:** two or more concurrent or sequential epidemics or disease clusters in a population with biological interactions, which exacerbate the prognosis and burden of disease

**Syringe Service Programs or Syringe Exchange Programs (SSPs/SEPs):** community-based prevention programs that can provide a range of services, including: access to and disposal of sterile syringes and injection equipment, linkage to substance use disorder treatment, distribution of naloxone, a medication that reverses overdoses, vaccination, testing, linkage to treatment for infectious diseases, including HIV and hepatitis B and C, education about overdose prevention and safer injection practices, abscess and wound care, and referral to social, mental health, and other medical services

