---
title: "End The Syndemic"
author: "DataLab"
date: '2022'
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bg: "#FAFBFE"
      fg: "#555555" 
      primary: "#91BAA7"
      navbar-bg: "#9A77C7"
      base_font: 
        google: Prompt
      heading_font:
        google: Open Sans
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: sans_serif
          local: false  
    orientation: row
    vertical_layout: fill
    
---

```{r setup, include=FALSE}

library(flexdashboard)
library(shiny)
library(tidyverse)
library(DT)
library(plotly)
library(leaflet)
library(leaflet.extras)
library(gsheet)
library(rgdal)
library(raster)
library(tigris)
library(RColorBrewer)
library(ggVennDiagram)
library(forcats)
library(lubridate)

pdf(NULL)

setwd("D:/DataLab/syndemic")

# Reading in data of locations of SEP
locations<-gsheet2tbl("https://docs.google.com/spreadsheets/d/1sb4P_7-UkcpkmENZ_DpMI45wRY7oItIFbv-0suLmz7U/edit?usp=sharing")
# Creating a column named label
locations<-locations %>% mutate(label = paste0("Name : ",name,"<br/>"," Address :",address,"<br/>","Phone :",phone,"<br/>" ) %>% lapply(htmltools::HTML))

# Reading in master data
masterdata<-read_csv("masterdata.csv")

# Reading in population by county data
popbycounty<-read_csv("SDC_TN_PL20_CountyPopChange.csv") 
popbycounty<-popbycounty %>% dplyr::select(County,`Population 2020`) %>% rename(county = County) %>% mutate(county = paste(county,"County"))

# Reading in data of zip codes and their county name
zips<-read.csv("countybyid.csv")

# Merging master data with county by ids
masterdata<-inner_join(zips,masterdata, by = "...1" ) %>% filter(state == "TN")
masterdata<-inner_join(popbycounty,masterdata, by = "county")

# Reading in spatial polygon data for map
s <- shapefile("D:/DataLab/tl_2021_us_county") 
boundaries <-subset(s, s@data$STATEFP == "47")

# Making color pallet based on SUD in county
paldata<-masterdata %>% filter(sud) %>% group_by(county) %>% summarise(total = n())

# Adding county total to spatial data frame
boundaries<-geo_join(boundaries, paldata, by_sp ="NAMELSAD" , by_df ="county")
boundaries<-geo_join(boundaries, popbycounty, by_sp = "NAMELSAD", by_df ="county")
boundaries@data<-boundaries@data %>% mutate(percap = total/Population.2020)

# Creating a palette to shade in the counties
pal <- colorNumeric(
  palette = "Reds",
  domain = boundaries@data$total)

#
syringes <- makeAwesomeIcon(
  icon = "hospital user",
  iconColor = "#FAFBFE",
  markerColor ="purple",
  library = "fa"
)

```

```{r reactive}

df_map<-reactive({
  
  if("All" %in% input$county_select){
    return(boundaries)
  }
  # Select only counties that have been selected!
  df<-subset(boundaries, boundaries@data$NAMELSAD %in% input$county_select)
  return(df)

})



```


Important Visuals!
=======================================

Sidebar {.sidebar}
---------------------------------------
###

```{r sidebar}

```


Row
---------------------------------------

###

```{r}


```

Visualizing Cost!
=======================================

Sidebar {.sidebar}
---------------------------------------
###

```{r sideba}

```

Row {.tabset .tabset-fade}
---------------------------------------

### Graph 1

```{r}

#Sets up an object that groups by primary payer, 
#sums the total costs each payer paid for syndemic patients,
#only saves the top 5,
#and then adds a new column, gov, for if it was funded by the government or not
md_top_payers <- masterdata %>% 
  filter(sud, endo | sstvi) %>% 
  group_by(Primary_Payer_Class_Cd) %>%
  summarise(total = sum(Total_Tot_Chrg)) %>% 
  arrange(desc(total)) %>% 
  head(5) %>% 
  mutate(gov = ifelse(Primary_Payer_Class_Cd %in% c('M','K','J', '8'), TRUE, FALSE))

#Renames the primary payers to their common name
md_top_payers$Primary_Payer_Class_Cd <- fct_recode(md_top_payers$Primary_Payer_Class_Cd,
             'Medicare' = 'M',
             'Medicare Advantage' = 'K',
             'Self-Pay' = 'P',
             'Blue Care' = 'J',
             'Americhoice' = '8')

renderPlot({
  
  #Plots the top 5 primary payers by their costs paid for syndemic patients
ggplot(data = md_top_payers, 
       aes(y = total/100000000, 
           x = reorder(Primary_Payer_Class_Cd, -total), 
           fill = gov ) ) +
  geom_col() +
  labs(title = 'Total Costs Covered by Top 5 Healthcare Providers',
       subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
       caption = 'End the Syndemic | DataLab 2022',
       x = 'Primary Provider',
       y = 'Cost Paid (in millions of US dollars)') +
  scale_fill_manual(md_top_payers, values = c('#1B365D', '#C11701'), 
                    labels = c('Privately Funded', 'Government Funded', '', '', ''),
                    name = 'Color Legend:') +
  theme(legend.position = 'bottom') +
  theme(axis.text.x = element_text(angle = 10))
  
})

```

### Graph 2

```{r}
#creates a object that groups by primary payer, summaries total paid by provider,
#and then adds gov columns to determine if government funded or privately funded
md_big_gov <- masterdata %>% 
  filter(sud, endo | sstvi) %>% 
  group_by(Primary_Payer_Class_Cd) %>% 
  summarise(total = sum(Total_Tot_Chrg)) %>% 
  arrange(desc(total)) %>% 
  mutate(gov = ifelse(Primary_Payer_Class_Cd %in% c('C','D','M','W','N','K','J',11, 12, 8, 10, 'Q', 'T'), 
                      'Government Funded', 
                      'Privately Funded'))

#Plots government vs private total funding for syndemic patients
ggplot(data = md_big_gov, 
       aes(y = total/100000000, 
           x = gov, 
           fill = gov ) ) +
  geom_col() +
  labs(title = 'Total Costs Paid by Government and Private Providers',
       caption = 'End the Syndemic | DataLab 2022',
       subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
       x = 'Primary Payer',
       y = 'Cost Paid (in millions of US dollars)') +
  scale_fill_manual(md_top_payers, values = c('#C11701', '#1B365D')) +
  theme(legend.position = '0')

```

### Graph 3

```{r}

#Creates a list of SUDs & ENDO or SSTVI for the ggvenn package to read
syndemic_list <- 
  list('SUDs' = which(masterdata$sud), 
       'SSTVIs or Endocarditis' = which(masterdata$endo | masterdata$sstvi))

#Creates a venn diagram showing overlap in SUDS and syndemic related ICD-10s
ggVennDiagram(syndemic_list,
              label_size = 4,
              label_alpha = 0.3,
              label = c('count')) +
  theme(legend.position = '0') +
  labs(title = 'Hospitalization overlap for substance use disorder (SUDs) and infectious sequela of interest',
       subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
       caption = 'End the Syndemic | DataLab 2022') +
  scale_color_manual(values = c('black','black')) +
  scale_fill_gradientn(colors = c('#555555', '#C11701', '#555555', '#1B365D'))

```


Map of Syringe Exchange Programs!
=======================================

Sidebar {.sidebar}
---------------------------------------
###

```{r loc_inp}

masterdatacountys<-masterdata %>% pull(county) %>% unique() %>% sort()

selectInput("county_select",
            "Choose county",
            choices = c("All",masterdatacountys),
            multiple = TRUE,
            selected = "All")

```

###

<font size="3" color = "#1B365D"> *This is a map from 2019, where each purple pin marks the location of a Syringe Exchange Clinic in the state of Tennessee.* 

**Glossary :** *Substance Use Disorder ( SUD )*</font>


Row
---------------------------------------

###

```{r}
renderValueBox({
  
  sepcount<-nrow(locations)
  
  valueBox("# of Syringe Exchange Programs in TN",
           value = sepcount,
           icon = "fa-syringe")
})
```

###

```{r}
renderValueBox({
  valueBox("# Counties in TN",
           value = 95,
           icon = "fa-building")
})
```

###

```{r}
renderValueBox({
  valueBox("# of people in TN",
           value = "6,910,840",
           icon = "fa-users")
})
```

Row
---------------------------------------

### Map

```{r}
renderLeaflet({
  # Map of just the markers
leaflet(locations) %>% # Adding map in the background
  addProviderTiles(providers$OpenStreetMap) %>% # Making the markers what we want
  addAwesomeMarkers(label = ~label, icon = syringes )%>% # Adding the boundaries of counties 
  addPolygons(data = df_map(),
              color ="#FAFBFE",
              fillColor = ~pal(total),
              fillOpacity = .6,
              weight = 2,
              opacity = .9,
              highlightOptions = highlightOptions(color = "#C11701", bringToFront = TRUE ),
              label = paste0("County : ",df_map()@data$NAMELSAD,"<br/>"," Cases of SUD  : ",df_map()@data$total) %>% lapply(htmltools::HTML)) %>% # Adding the option of zooming into your current loc
  addControlGPS(options = gpsOptions(position = "topleft", activate = TRUE, 
                                             autoCenter = TRUE, maxZoom = 200, 
                                             setView = TRUE)) %>% # Adding legend explaining the shading
    addLegend(pal = pal, 
            values = boundaries@data$total, 
            opacity = 0.7, 
            title = htmltools::HTML("Total SUD cases <br>
                                    by County <br>
                                    2019"),
            position = "bottomright")
  
})
```

```{r}
ui<-fluidPage(
  
)

server<-function(input, ouput, session) {
  
}

shinyApp(ui,server)
```
