---
title: "End The Syndemic"
author: "DataLab"
date: '2022'
runtime: shiny
output:
  flexdashboard::flex_dashboard:
    theme:
      version: 4
      bg: "#FAFBFE"
      fg: "#555555" 
      primary: "#91BAA7"
      navbar-bg: "#9A77C7"
      base_font: 
        google: Prompt
      heading_font:
        google: Open Sans
      code_font:
        google: 
          # arguments to sass::font_google() 
          family: sans_serif
          local: false
    vertical_layout: fill
    
---

```{r setup, include=FALSE}

library(flexdashboard)
library(shiny)
library(tidyverse)
library(DT)
library(plotly)
library(leaflet)
library(leaflet.extras)
library(gsheet)
library(rgdal)
library(raster)
library(tigris)
library(RColorBrewer)
library(ggVennDiagram)
library(forcats)
library(lubridate)
library(patchwork)

pdf(NULL)

setwd("/Users/erteam/Desktop/Syndemic Project/syndemic")

# Reading in data of locations of SEP
locations<-gsheet2tbl("https://docs.google.com/spreadsheets/d/1sb4P_7-UkcpkmENZ_DpMI45wRY7oItIFbv-0suLmz7U/edit?usp=sharing")
# Creating a column named label
locations<-locations %>% mutate(label = paste0("Name : ",name,"<br/>"," Address :",address,"<br/>","Phone :",phone,"<br/>" ) %>% lapply(htmltools::HTML))

# Reading in master data
masterdata<-read_csv("masterdataphi.csv")

# Reading in population by county data
popbycounty<-read_csv("SDC_TN_PL20_CountyPopChange.csv") 
popbycounty<-popbycounty %>% dplyr::select(County,`Population 2020`) %>% rename(county = County) %>% mutate(county = paste(county,"County"))

# Reading in data of zip codes and their county name
zips<-read.csv("countybyid.csv")

# Merging master data with county by ids
masterdata<-inner_join(zips,masterdata, by = "...1" ) %>% filter(state == "TN")
masterdata<-inner_join(popbycounty,masterdata, by = "county")

# Reading in spatial polygon data for map
s <- shapefile("/Users/erteam/Desktop/Syndemic Project/tl_2021_us_county") 
boundaries <-subset(s, s@data$STATEFP == "47")

# Making color pallet based on SUD in county
paldata<-masterdata %>% filter(sud) %>% group_by(county) %>% summarise(total = n())

# Adding county total to spatial data frame
boundaries<-geo_join(boundaries, paldata, by_sp ="NAMELSAD" , by_df ="county")
boundaries<-geo_join(boundaries, popbycounty, by_sp = "NAMELSAD", by_df ="county")
boundaries@data<-boundaries@data %>% mutate(percap = (total/Population.2020)*100)

mean(boundaries@data$percap)

pal <- colorNumeric(
  palette = "Reds",
  domain = boundaries@data$percap)

#
syringes <- makeAwesomeIcon(
  icon = "hospital user",
  iconColor = "#FAFBFE",
  markerColor ="purple",
  library = "fa"
)

```

```{r reactive}

df_map<-reactive({
  
  if("All" %in% input$county_select){
    return(boundaries)
  }
  # Select only counties that have been selected!
  df<-subset(boundaries, boundaries@data$NAMELSAD %in% input$county_select)
  return(df)

})



```

Home Page {data-orientation=rows}
=======================================

Row {.tabset}
---------------------------------------

### End The Syndemic

Syndemic made of two or more pandemics with combined biological factors that cause a syndemic

### Who is this for?

For everyone, more specifically Tennessee Residents

### Navigating the dashboard.

Plotly

Important Visuals! {style="position:relative;"}
=======================================

Sidebar {.sidebar}
---------------------------------------
###

```{r sidebar}

```

Column {style="height:200pc;"}
---------------------------------------

### Graph 1

```{r}
md_phi<-masterdata
#Formats data, adds a months column, makes an age groups column and then a quarter columns for the year
md_phi_jacob <- 
  md_phi %>% 
  mutate(creation_dt = mdy(creation_dt)) %>% 
  mutate(months = month(creation_dt)) %>% 
  mutate(Age_Groups = ifelse(Age %in% 0:17, '0-17', 
                             ifelse(Age %in% 18:24, '18-24',
                                    ifelse(Age %in% 25:34, '25-34',
                                           ifelse(Age %in% 35:44, '35-44',
                                                  ifelse(Age %in% 45:54, '45-54',
                                                         ifelse(Age %in% 55:64, '55-64', '65+'))))))) %>% 
  mutate(quarter = ifelse(months %in% 1:3, 1,
                          ifelse(months %in% 4:6, 2,
                                 ifelse(months %in% 7:9, 3, 4)))) 


#Plots SUDS and endo
  b1<-ggplotly(ggplot(data = md_phi_jacob %>% 
         filter(!Age_Groups == '65+', !Age_Groups == '0-17', sud&endo) %>% 
         group_by(Age_Groups, quarter) %>% 
         tally(),
      aes(x = quarter,
          y = n,
          color = Age_Groups)) +
  geom_point() +
  geom_line() +
  labs(title = 'Trends in Hospitalization for Substance Abuse and Endocarditis',
       subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
       caption = 'End the Syndemic | DataLab 2022',
       x = 'Yearly Quarter',
       y = 'Total Patients') +
  scale_color_manual(values = c('#C11701', '#B1B1B1', '#1B365D', '#9A77C7', '#91BAA7')), showlegend = FALSE)

  
  #Plots SUDS and osteo
    b2<-ggplotly(ggplot(data = md_phi_jacob %>% 
         filter(!Age_Groups == '65+', !Age_Groups == '0-17', sud&ost) %>% 
         group_by(Age_Groups, quarter) %>% 
         tally(),
       aes(x = quarter,
           y = n,
           color = Age_Groups)) +
  geom_point() +
  geom_line() +
  labs(title = 'Trends in Hospitalization for Substance Abuse and Ostemyelitis',
       subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
       caption = 'End the Syndemic | DataLab 2022',
       x = 'Yearly Quarter',
       y = 'Total Patients') +
  scale_color_manual(values = c('#C11701', '#B1B1B1', '#1B365D', '#9A77C7', '#91BAA7')))
  
    
  #Plots SUDS and sepsis
b3<-ggplotly(ggplot(data = md_phi_jacob%>% 
         filter(!Age_Groups == '65+', !Age_Groups == '0-17', sud&sepsis) %>% 
         group_by(Age_Groups, quarter) %>% 
         tally(),
       aes(x = quarter,
           y = n,
           color = Age_Groups)) +
  geom_point() +
  geom_line() +
  labs(title = 'Trends in Hospitalization for Substance Abuse and Sepsis',
       subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
       caption = 'End the Syndemic | DataLab 2022',
       x = 'Yearly Quarter',
       y = 'Total Patients') +
  scale_color_manual(values = c('#C11701', '#B1B1B1', '#1B365D', '#9A77C7', '#91BAA7')))
  
  
  #Plots SUDS and sstvi
b4<-ggplotly(ggplot(data = md_phi_jacob %>% 
         filter(!Age_Groups == '65+', !Age_Groups == '0-17', sud&sstvi) %>% 
         group_by(Age_Groups, quarter) %>% 
         tally(),
       aes(x = quarter,
           y = n,
           color = Age_Groups)) +
  geom_point() +
  geom_line() +
  labs(title = 'Trends in Hospitalization for Substance Abuse and all SSTVIs',
       subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
       caption = 'End the Syndemic | DataLab 2022',
       x = 'Yearly Quarter',
       y = 'Total Patients') +
  scale_color_manual(values = c('#C11701', '#B1B1B1', '#1B365D', '#9A77C7', '#91BAA7')))

annotations = list( 
  list( 
    x = 0.2,  
    y = 1.0,  
    text = "Trends in Hospitalizations for Substance Abuse and Endocarditis",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.8,  
    y = 1,  
    text = "Trends in Hospitalizations for Substance Abuse and Osteomyelitis",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.2,  
    y = 0.49,  
    text = "Trends in Hospitalizations for Substance Abuse and Sepsis",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),
  list( 
    x = 0.8,  
    y = 0.49,  
    text = "Trends in Hospitalization for Substance Abuse and all SSTVIs",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ))
  
subplot(style(b1,showlegend = FALSE),style(b2,showlegend = FALSE),style(b3,showlegend = FALSE),b4,nrows = 2, shareX = TRUE ) %>% layout(title = "Trends over time for Substance Abuse" , annotations = annotations)

```

### Graph 5

```{r}

  
  #Plots SUDS and SSTVI or Endo
ggplotly(ggplot(data = md_phi_jacob %>% 
         filter(!Age_Groups == '65+', !Age_Groups == '0-17', sud, endo | sstvi) %>% 
         group_by(Age_Groups, quarter) %>% 
         tally(),
       aes(x = quarter,
           y = n,
           color = Age_Groups)) +
  geom_point() +
  geom_line() +
  labs(title = 'Trends in Hospitalization for Substance Abuse and all SSTVIs or Endocarditis',
       subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
       caption = 'End the Syndemic | DataLab 2022',
       x = 'Yearly Quarter',
       y = 'Total Patients') +
  scale_color_manual(values = c('#C11701', '#B1B1B1', '#1B365D', '#9A77C7', '#91BAA7')))
  

```

### Graph 6

```{r}

  
  ggplotly(ggplot(data = md_phi_jacob %>%  mutate(creation_dt = mdy(creation_dt)) %>% 
         mutate(months = month(creation_dt)) %>% 
         mutate(quarter = ifelse(months %in% 1:3, 1,
                                 ifelse(months %in% 4:6, 2,
                                        ifelse(months %in% 7:9, 3, 4)))),
       aes(x = quarter)) +
  geom_bar())

  

```


Visualizing Cost! {data-orientation=rows}
=======================================

Sidebar {.sidebar}
---------------------------------------
###

```{r sideba}

```

Row {.tabset .tabset-fade}
---------------------------------------

### Graph 1

```{r}

#Sets up an object that groups by primary payer, 
#sums the total costs each payer paid for syndemic patients,
#only saves the top 5,
#and then adds a new column, gov, for if it was funded by the government or not
md_top_payers <- masterdata %>% 
  filter(sud, endo | sstvi) %>% 
  group_by(Primary_Payer_Class_Cd) %>%
  summarise(total = sum(Total_Tot_Chrg)) %>% 
  arrange(desc(total)) %>% 
  head(5) %>% 
  mutate(gov = ifelse(Primary_Payer_Class_Cd %in% c('M','K','J', '8'), TRUE, FALSE))

#Renames the primary payers to their common name
md_top_payers$Primary_Payer_Class_Cd <- fct_recode(md_top_payers$Primary_Payer_Class_Cd,
             'Medicare' = 'M',
             'Medicare Advantage' = 'K',
             'Self-Pay' = 'P',
             'Blue Care' = 'J',
             'Americhoice' = '8')
  
  #Plots the top 5 primary payers by their costs paid for syndemic patients
a1<-ggplotly(ggplot(data = md_top_payers, 
       aes(y = total/100000000, 
           x = reorder(Primary_Payer_Class_Cd, -total), 
           fill = gov ) ) +
  geom_col() +
  labs(title = 'Total Costs Covered by Top 5 Healthcare Providers',
       subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
       caption = 'End the Syndemic | DataLab 2022',
       x = 'Primary Provider',
       y = 'Cost Paid (in millions of US dollars)') +
  scale_fill_manual(md_top_payers, values = c('#1B365D', '#C11701'), 
                    labels = c('Privately Funded', 'Government Funded', '', '', ''),
                    name = 'Color Legend:') +
  theme(legend.position = 'bottom') +
  theme(axis.text.x = element_text(angle = 10)))
  

#creates a object that groups by primary payer, summaries total paid by provider,
#and then adds gov columns to determine if government funded or privately funded
md_big_gov <- masterdata %>% 
  filter(sud, endo | sstvi) %>% 
  group_by(Primary_Payer_Class_Cd) %>% 
  summarise(total = sum(Total_Tot_Chrg)) %>% 
  arrange(desc(total)) %>% 
  mutate(gov = ifelse(Primary_Payer_Class_Cd %in% c('C','D','M','W','N','K','J',11, 12, 8, 10, 'Q', 'T'), 
                      'Government Funded', 
                      'Privately Funded'))
  
#Plots government vs private total funding for syndemic patients
a2<-ggplotly(ggplot(data = md_big_gov, 
       aes(y = total/100000000, 
           x = gov, 
           fill = gov ) ) +
  geom_col() +
  labs(title = 'Total Costs Paid by Government and Private Providers',
       caption = 'End the Syndemic | DataLab 2022',
       subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
       x = 'Primary Payer',
       y = 'Cost Paid (in millions of US dollars)') +
  scale_fill_manual(md_top_payers, values = c('#C11701', '#1B365D'), 
                    labels = c('Privately Funded', 'Government Funded'),
                    name = 'Color Legend:'))
  
subplot(a2,style(a1, showlegend=F))

```

### Graph 3

```{r, echo=FALSE}

#Creates a list of SUDs & ENDO or SSTVI for the ggvenn package to read
syndemic_list <- 
  list('SUDs' = which(masterdata$sud), 
       'SSTVIs or Endocarditis' = which(masterdata$endo | masterdata$sstvi))

#Creates a venn diagram showing overlap in SUDS and syndemic related ICD-10s
ggVennDiagram(syndemic_list,
              label_size = 4,
              label_alpha = 0.3,
              label = c('count')) +
  theme(legend.position = '0') +
  labs(title = 'Hospitalization overlap for substance use disorder (SUDs) and infectious sequela of interest',
       subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
       caption = 'End the Syndemic | DataLab 2022') +
  scale_color_manual(values = c('black','black')) +
  scale_fill_gradientn(colors = c('#555555', '#C11701', '#555555', '#1B365D'))

```

### Graphs

```{r}

 #Adds a gov column, private or publicly funded, to md_phi
md_phi_jacob <- md_phi_jacob %>%
  mutate(gov = ifelse(Primary_Payer_Class_Cd %in% c('C','D','M','W','N','K','J',11, 12, 8, 10, 'Q', 'T'), 
                      'Government Funded', 
                      'Privately Funded'))

#Changes format of # from exponential to normal
options(scipen = 999)

#Plots SUDS and endo
g1<-ggplotly(ggplot(data = md_phi_jacob %>% 
         filter(sud,endo),
       aes(x = quarter,
           y = Total_Tot_Chrg/100,
           fill = gov)) +
  geom_col(position = 'dodge') +   
  labs(title = 'Trends in Costs for Substance Abuse and Endocarditis',
                      subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
                      caption = 'End the Syndemic | DataLab 2022',
                      x = 'Yearly Quarter',
                      y = 'Cost (In US Dollars)',
       fill = 'Primary Payer:') +
  theme(legend.position = 'none') +
  scale_fill_manual(values = c('#C11701', '#1B365D')))


  #Adds a gov column, private or publicly funded, to md_phi
md_phi_jacob <- md_phi_jacob %>%
  mutate(gov = ifelse(Primary_Payer_Class_Cd %in% c('C','D','M','W','N','K','J',11, 12, 8, 10, 'Q', 'T'), 
                      'Government Funded', 
                      'Privately Funded'))


  
  #Plots SUDS and ost
g2<-ggplotly(ggplot(data = md_phi_jacob %>% 
         filter(sud, ost),
       aes(x = quarter,
           y = Total_Tot_Chrg/100,
           fill = gov)) +
  geom_col(position = 'dodge') +
  labs(title = 'Trends in Costs for Substance Abuse and Osteomyelitis',
                      subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
                      caption = 'End the Syndemic | DataLab 2022',
                      x = 'Yearly Quarter',
                      y = 'Cost (In US Dollars)',
       fill = 'Primary Payer:') +
  theme(legend.position = 'none') +
  scale_fill_manual(values = c('#C11701', '#1B365D')))

  #Adds a gov column, private or publicly funded, to md_phi
md_phi_jacob <- md_phi_jacob %>%
  mutate(gov = ifelse(Primary_Payer_Class_Cd %in% c('C','D','M','W','N','K','J',11, 12, 8, 10, 'Q', 'T'), 
                      'Government Funded', 
                      'Privately Funded'))


  
  #Plots SUDS and sepsis
g3<-ggplotly(ggplot(data = md_phi_jacob %>% 
         filter(sud, sepsis),
       aes(x = quarter,
           y = Total_Tot_Chrg/100,
           fill = gov)) +
  geom_col(position = 'dodge') +
  labs(title = 'Trends in Costs for Substance Abuse and Sepsis',
                      subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
                      caption = 'End the Syndemic | DataLab 2022',
                      x = 'Yearly Quarter',
                      y = 'Cost (In US Dollars)',
       fill = 'Primary Payer:') +
  theme(legend.position = 'none') +
  scale_fill_manual(values = c('#C11701', '#1B365D')))
  

  #Adds a gov column, private or publicly funded, to md_phi
md_phi_jacob <- md_phi_jacob %>%
  mutate(gov = ifelse(Primary_Payer_Class_Cd %in% c('C','D','M','W','N','K','J',11, 12, 8, 10, 'Q', 'T'), 
                      'Government Funded', 
                      'Privately Funded'))


  
  #Plots SUDS and SSTVIs
g4<-ggplotly(ggplot(data = md_phi_jacob %>% 
         filter(sud, sstvi),
       aes(x = quarter,
           y = Total_Tot_Chrg/100,
           fill = gov)) +
  geom_col(position = 'dodge') +
  labs(title = 'Trends in Costs for Substance Abuse and all SSTVIs',
                      subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
                      caption = 'End the Syndemic | DataLab 2022',
                      x = 'Yearly Quarter',
                      y = 'Cost (In US Dollars)',
       fill = 'Primary Payer:') +
  theme(legend.position = 'bottom') +
  scale_fill_manual(values = c('#C11701', '#1B365D')))

annotations = list( 
  list( 
    x = 0.2,  
    y = 1.0,  
    text = "Trends in Costs for Substance Abuse and Endocarditis",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.8,  
    y = 1,  
    text = "Trends in Costs for Substance Abuse and Osteomyelitis",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.2,  
    y = 0.49,  
    text = "Trends in Costs for Substance Abuse and Sepsis",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),
  list( 
    x = 0.8,  
    y = 0.49,  
    text = "Trends in Costs for Substance Abuse and all SSTVIs",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ))

subplot(style(g1,showlegend = FALSE),style(g2,showlegend = FALSE),style(g3,showlegend = FALSE),g4,nrows = 2, shareX = TRUE, shareY = TRUE ) %>% layout(title = "Trends in Cost for Substance Abuse" , annotations = annotations)
  
```

### Graph 8

```{r}

  #Adds a gov column, private or publicly funded, to md_phi
md_phi_jacob <- md_phi_jacob %>%
  mutate(gov = ifelse(Primary_Payer_Class_Cd %in% c('C','D','M','W','N','K','J',11, 12, 8, 10, 'Q', 'T'), 
                      'Government Funded', 
                      'Privately Funded'))

renderPlotly({
  
  #Plots SUDS and SSTVIs or Endo
ggplotly(ggplot(data = md_phi_jacob %>% 
         filter(sud, sstvi|endo),
       aes(x = quarter,
           y = Total_Tot_Chrg/100,
           fill = gov)) +
  geom_col(position = 'dodge') +
  labs(title = 'Trends in Costs for Substance Abuse and Endocarditis or a SSTVI',
       subtitle = 'TN Hospitals 2019 | Inpatient and Outpatient',
       caption = 'End the Syndemic | DataLab 2022',
       x = 'Yearly Quarter',
       y = 'Cost (In US Dollars)',
       fill = 'Primary Payer:') +
  theme(legend.position = 'bottom') +
  scale_fill_manual(values = c('#C11701', '#1B365D')))

  
})

```

Map of Syringe Exchange Programs! {data-orientation=rows}
=======================================

Sidebar {.sidebar}
---------------------------------------
###

```{r loc_inp}

masterdatacountys<-masterdata %>% pull(county) %>% unique() %>% sort()

selectInput("county_select",
            "Choose county",
            choices = c("All",masterdatacountys),
            multiple = TRUE,
            selected = "All")

```

###

<font size="3" color = "#1B365D"> *This is a map from 2019, where each purple pin marks the location of a Syringe Exchange Clinic in the state of Tennessee.* 

**Glossary :** *Substance Use Disorder ( SUD )*</font>


Row
---------------------------------------

###

```{r}
renderValueBox({
  
  sepcount<-nrow(locations)
  
  valueBox("# of Syringe Exchange Programs in TN",
           value = sepcount,
           icon = "fa-syringe")
})
```

###

```{r}
renderValueBox({
  valueBox("# Counties in TN",
           value = 95,
           icon = "fa-building")
})
```

###

```{r}
renderValueBox({
  valueBox("# of people in TN",
           value = "6,910,840",
           icon = "fa-users")
})
```

Row
---------------------------------------

### Map

```{r}
renderLeaflet({
  
leaflet(locations) %>%
  addProviderTiles(providers$OpenStreetMap) %>% 
  addAwesomeMarkers(label = ~label, icon = syringes )%>%
  addPolygons(data = df_map(),
              color ="#FAFBFE",
              fillColor = ~pal(percap),
              fillOpacity = .6,
              weight = 2,
              opacity = .9,
              highlightOptions = highlightOptions(color = "#C11701", bringToFront = TRUE ),
              label = paste0("County : ",df_map()@data$NAMELSAD,"<br/>"," Percent of SUD in total : ",df_map()@data$percap) %>% lapply(htmltools::HTML)) %>% 
  addControlGPS(options = gpsOptions(position = "topleft", activate = TRUE, 
                                             autoCenter = TRUE, maxZoom = 200, 
                                             setView = TRUE)) %>% 
    addLegend(pal = pal, 
            values = boundaries@data$percap, 
            opacity = 0.7, 
            title = htmltools::HTML("Percentage of SUD cases <br>
                                    by County <br>
                                    2019"),
            position = "bottomright")
  
})
```

About Us 
=======================================

Column
---------------------------------------

### DataLab 2022

```{r}
```

Column .tabset}
---------------------------------------

### Delana

```{r}
```

### Alan

### Jacob

### Amber

```{r}
ui<-fluidPage(
  
)

server<-function(input, ouput, session) {
  
}

shinyApp(ui,server)
```
